name: Debug Secrets

on:
  workflow_dispatch:


jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Zeige aktuelle Branch-Info (optional)
      run: 'echo "Branch: $GITHUB_REF"'

    - name: Spieler-IDs Länge testen
      env:
        PLAYER_IDS: ${{ secrets.PLAYER_IDS }}
      run: |
        echo "PLAYER_IDS Länge: ${#PLAYER_IDS}"
        echo "Inhalt Vorschau (1. Zeile):"
        echo "$PLAYER_IDS" | head -n 1
